### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by ghost** [1C3/ICEcons#5] opened 2016-05-14 11:04 UTC
Hello

Habe some icons that i need

BlaBlaCar (Google Play)
c:geo (Google Play)
Cabinet Beta (fdroid)
DAVdroid(fdroid)
Etar(fdroid)
Fennec F-Droid
Google (Google Play)
Kalenderfarben(fdroid)
KeePassDroid(fdroid)
LeafPic(fdroid)
LibreSignal(fdroid)
RadioDroid(fdroid)
RunnerUp(fdroid)
Sieben(FDroid)
Waze(Google Play)
Wunderlist(Google Play)

``` xml
<!-- BlaBlaCar -->
<item component="ComponentInfo{com.comuto/com.comuto.v3.activity.ProxyActivity}" drawable="com_comuto_com_comuto_v3_activity_ProxyActivity"/>
<!-- c:geo -->
<item component="ComponentInfo{cgeo.geocaching/cgeo.geocaching.MainActivity}" drawable="cgeo_geocaching_cgeo_geocaching_MainActivity"/>
<!-- Cabinet Beta -->
<item component="ComponentInfo{com.afollestad.cabinet/com.afollestad.cabinet.ui.MainActivity}" drawable="com_afollestad_cabinet_com_afollestad_cabinet_ui_MainActivity"/>
<!-- DAVdroid -->
<item component="ComponentInfo{at.bitfire.davdroid/at.bitfire.davdroid.ui.AccountsActivity}" drawable="at_bitfire_davdroid_at_bitfire_davdroid_ui_AccountsActivity"/>
<!-- Etar -->
<item component="ComponentInfo{ws.xsoh.etar/com.android.calendar.AllInOneActivity}" drawable="ws_xsoh_etar_com_android_calendar_AllInOneActivity"/>
<!-- Fennec F-Droid -->
<item component="ComponentInfo{org.mozilla.fennec_fdroid/org.mozilla.fennec_fdroid.App}" drawable="org_mozilla_fennec_fdroid_org_mozilla_fennec_fdroid_App"/>
<!-- Google -->
<item component="ComponentInfo{com.google.android.googlequicksearchbox/com.google.android.googlequicksearchbox.SearchActivity}" drawable="com_google_android_googlequicksearchbox_com_google_android_googlequicksearchbox_SearchActivity"/>
<!-- Kalenderfarben -->
<item component="ComponentInfo{ch.ihdg.calendarcolor/ch.ihdg.calendarcolor.CalendarListActivity}" drawable="ch_ihdg_calendarcolor_ch_ihdg_calendarcolor_CalendarListActivity"/>
<!-- KeePassDroid -->
<item component="ComponentInfo{com.android.keepass/com.android.keepass.KeePass}" drawable="com_android_keepass_com_android_keepass_KeePass"/>
<!-- LeafPic -->
<item component="ComponentInfo{com.horaapps.leafpic/com.horaapps.leafpic.SplashScreen}" drawable="com_horaapps_leafpic_com_horaapps_leafpic_SplashScreen"/>
<!-- LibreSignal -->
<item component="ComponentInfo{org.libresignal/org.thoughtcrime.securesms.RoutingActivity}" drawable="org_libresignal_org_thoughtcrime_securesms_RoutingActivity"/>
<!-- RadioDroid -->
<item component="ComponentInfo{net.programmierecke.radiodroid2/net.programmierecke.radiodroid2.ActivityMain}" drawable="net_programmierecke_radiodroid2_net_programmierecke_radiodroid2_ActivityMain"/>
<!-- RunnerUp -->
<item component="ComponentInfo{org.runnerup/org.runnerup.view.MainLayout}" drawable="org_runnerup_org_runnerup_view_MainLayout"/>
<!-- Sieben -->
<item component="ComponentInfo{de.baumann.sieben/de.baumann.sieben.MainActivity}" drawable="de_baumann_sieben_de_baumann_sieben_MainActivity"/>
<!-- Waze -->
<item component="ComponentInfo{com.waze/com.waze.FreeMapAppActivity}" drawable="com_waze_com_waze_FreeMapAppActivity"/>
<!-- Wunderlist -->
<item component="ComponentInfo{com.wunderkinder.wunderlistandroid/com.wunderkinder.wunderlistandroid.activity.WLMainFragmentActivity}" drawable="com_wunderkinder_wunderlistandroid_com_wunderkinder_wunderlistandroid_activity_WLMainFragmentActivity"/>

```

**Comment by atmtck** [comment] 2016-05-14 17:12
Thank you for providing the necessary componentinfo, I'm quite busy with other projects right now but I should be able to add all the icons before the end of the next week, together with the other pending requests

**Comment by ghost** [comment] 2016-05-14 17:21
Really cool thanks for it

**Comment by baconicsynergy** [comment] 2016-05-14 23:38
This shall be the greateat icon pack in all the land

**Comment by conrad-heimbold** [comment] 2016-05-15 17:58
The problem with icons from companies like BlaBlaCar is the following: they actually forbid you to change their logos / icons, have a look onto <a href="https://www.blablacar.de/news/impressum">BlaBlaCar's impressum</a> for example. (For BlaBlaCar, the good thing is, they allow you to use their content for "private, non-commercial use"; but that does not have to be the case for other companies). So you have to start from scratch and kind of re-invent those logos: it should still look like the original one (it should have a recognition value); but it also should not be too similar to the original one in order to not commit a copyright infringement. We all know: even if it is a copyright infringement, most companies don't care at all; but you still want to be on the safe side, don't you?

**Comment by atmtck** [comment] 2016-05-15 20:44
I'm not that worried about copyright because:
- all the icons have been drawn by me and no one else from the ground up, I haven't used or modified third party assets anywhere in this pack, even the ones that look very similar to the original like the google or the facebook  or skype icons have actually been drawn by me and are slightly different from the originals.
- other icon packs on the play store that actually use slightly modified versions of copyrighted logos or even just the originals with a filter, and are monetized, have been up for years without problems.
- I don't know how the law works in this situation, but I think that while some of my icons might be similar enough to the original to infringe copyright, I'm not using them to impersonate the entity and/or making money off their logo, so there might not be any ground for a lawsuit even if they decided to try and stop me.

**Comment by atmtck** [comment] 2016-05-15 20:47
Now that I think about it, wikipedia's is the only icon which contains external assets, but they have a very permissive policy so it's not a problem

**Comment by conrad-heimbold** [comment] 2016-05-15 20:58
OT: @1C3, can I help you and design some icons in Inkscape; or do you want to be the only maker of icons?

**Comment by atmtck** [comment] 2016-05-15 21:13
Not really, while I greatly enjoy the help with gathering information about the apps, I'd rather remain the only artist behind the pack.

**Comment by baconicsynergy** [comment] 2016-05-15 22:51
I think for the most part things should be fine, but I am concerned about the non-commercial licenses, as they are considered non-free

**Comment by atmtck** [comment] 2016-05-16 21:55
Release 2.5 is here, should also be on fdroid tomorrow, check it out and if everything is ok close the issue.
Also @baconicsynergy the icons which I inspire mine from might be non free, but they're not in the app so it doesn't matter, every graphical asset in my repo is free.

**Comment by ghost** [comment] 2016-05-17 07:54
Thanks for that wonderful icons.
Here are some next :)

And Bible
Clash Royale
FreeOTP
Kontakte
LibreSignal

``` xml
<!-- And Bible -->
<item component="ComponentInfo{net.bible.android.activity/net.bible.android.activity.StartupActivity}" drawable="net_bible_android_activity_net_bible_android_activity_StartupActivity"/>
<!-- Clash Royale -->
<item component="ComponentInfo{com.supercell.clashroyale/com.supercell.clashroyale.GameApp}" drawable="com_supercell_clashroyale_com_supercell_clashroyale_GameApp"/>
<!-- FreeOTP -->
<item component="ComponentInfo{org.fedorahosted.freeotp/org.fedorahosted.freeotp.MainActivity}" drawable="org_fedorahosted_freeotp_org_fedorahosted_freeotp_MainActivity"/>
<!-- Kontakte -->
<item component="ComponentInfo{com.android.contacts/com.android.contacts.activities.PeopleActivity}" drawable="com_android_contacts_com_android_contacts_activities_PeopleActivity"/>
<!-- LibreSignal -->
<item component="ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}" drawable="org_thoughtcrime_securesms_org_thoughtcrime_securesms_RoutingActivity"/>
```

**Comment by ghost** [comment] 2016-05-17 08:04
And there is an error with music.
Before the update I had an icon now it is gone

**Comment by atmtck** [comment] 2016-05-24 08:43
I added the requested icons and checked the music one but can't find anything wrong, are you sure the problem is not on your end ?

**Comment by ghost** [comment] 2016-05-24 08:50
Yeah the error is in my site sorry

**Closed as completed** 2016-05-24 10:12 UTC
